language: node_js
node_js: '10'
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - npm run lint
script:
  - npm run test
before_deploy:
  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
  - chmod -R u+x ./Bluemix_CLI/bin
  - chmod +x ./deploy.sh
  - npm run build
  - cd server/
  # Prevent deploy stage from timing out waiting for output. The function
  # literally rings a bell and the non-printable character can be found in
  # TravisCI output as black square.
  # Original solution can be found at:
  # https://github.com/travis-ci/dpl/issues/568#issuecomment-272465349
  - |
    function keep_alive() {
      while true; do
        echo -en "\a"
        sleep 5
      done
    }
    keep_alive &
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
  skip_cleanup: true
