language: node_js
node_js: "8"
cache:
  directories:
    - node_modules
before_script:
  - npm run lint
script:
  - echo "Test disabled temporarily"
  # - npm run test
before_deploy:
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
