language: node_js
node_js: "8"
cache:
  directories:
    - node_modules
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  - provider: cloudfoundry
    username: apikey
    password: $IBM_CLOUD_API_KEY
    api: https://api.ng.bluemix.net
    organization: $IBM_CLOUD_ORGANIZATION
    space: $IBM_CLOUD_SPACE
    manifest: manifest.yml
    on:
      branch: master
