language: node_js
node_js: '10'
cache:
  directories:
    - node_modules
before_script:
  - npm run lint
script:
  - npm run test
before_deploy:
  - npm run build
  - cd server/
  # Prevent deploy stage from timing out waiting for output. The function
  # literally rings a bell and the non-printable character can be found in
  # TravisCI output as black square.
  # Original solution can be found at:
  # https://github.com/travis-ci/dpl/issues/568#issuecomment-272465349
  - |
    function keep_alive() {
      while true; do
        echo -en "\a"
        sleep 5
      done
    }
    keep_alive &
deploy:
  - provider: cloudfoundry
    username: apikey
    password: $IBM_CLOUD_API_KEY
    api: https://api.ng.bluemix.net
    organization: $IBM_CLOUD_ORGANIZATION
    space: $IBM_CLOUD_SPACE
    app_name: Qiskit website
    on:
      branch: master