addons:
  apt:
    packages:
    - curl
language: node_js
node_js: '10'
cache:
  directories:
  - node_modules
jobs:
  - name: Lint, Tests, and Build
    script:
        - npm run lint
        - npm run test
        - npm run build
  - name: Build and Deploy
    if: type = push AND branch = master
    script:
      - npm run build
      - cd deploy && bash ./deploy_cos.sh
