language: node_js
node_js: '10'
cache:
  directories:
    - node_modules
before_script:
  - npm run lint
script:
  - npm run test
after_success:
  - npm run build
  - cd server/
before_deploy: |
  function keep_alive() {
    while true; do
      echo -en "\a"
      sleep 5
    done
  }
  keep_alive &
deploy:
  - provider: cloudfoundry
    username: apikey
    password: $IBM_CLOUD_API_KEY
    api: https://api.ng.bluemix.net
    organization: $IBM_CLOUD_ORGANIZATION
    space: $IBM_CLOUD_SPACE
    app_name: Qiskit website
    on:
      branch: master
