addons:
  apt:
    packages:
    - curl
language: node_js
node_js: '12'
cache: npm
jobs:
  include:
    - name: Lint, Tests, and Build
      if: type = pull_request
      script:
          - npm run lint
          - npm test
    - name: Build and Deploy
      if: (type = push OR type = cron) AND branch = master
      script:
        - npm run generate && cd deploy && bash ./deploy_cos.sh
